name: Build dylib

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Theos
        uses: waruhachi/theos-action@v2.6.3
        with:
          theos-src: 'theos/theos'
          theos-branch: 'master'
          sdks-src: 'theos/sdks'
          sdks-branch: 'master'

      - name: Build dylib
        run: |
          make clean
          make FINALPACKAGE=1

      - name: Find dylib
        run: |
          mkdir -p output
          find .theos -type f -name "*.dylib" -exec cp {} output/ \;
          ls -lh output

      - name: Upload dylib
        uses: actions/upload-artifact@v4
        with:
          name: VoiceRebuildInjectTest-dylib
          path: output/*.dylib
